AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
