AllCops:
  TargetRubyVersion: 2.3
  Include:
    - lib/**/*.rake
  Exclude:
    - config/**/*.rb
    - bin/*
    - db/schema.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Metrics:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
